### PR TITLE
Added a new GET function

### PR DESCRIPTION
**Pull request by dinilandy**
Added a new GET function in the comments controller that retrieves all messages of a specific discussion based on the DiscussionID. I also implemented the necessary functions in the DAL and BLL

### CODE REVIEW

**Review by RutiRozenberg — CHANGES_REQUESTED** [review]
Hi Dina 

In the file: `BLL/Interfaces/Comment.cs` :
- Remove any additional lines that were added to the file.
- Avoid adding extra lines and spaces in general.

In the file: `BLL/Services/Comment.cs ` :
- Update the documentation to Hebrew language.

In the file: ` WebApi/Controllers/CommentController.cs` :
- Add a blank line before the newly added function.
- Remove "discussion/" from the route string. This part is automatically added by the [Route("api/[controller]")] line at the top of the file. For each function, add the extension (without / at the beginning) to the beginning of the string.

**Comment by dinilandy** [comment]
hi,
I didn’t understand the instruction to update the documentation to Hebrew, as it is already written in Hebrew. Should I change it to English or remove it? It's not clear.
thanks

**Comment by RutiRozenberg** [comment]
sori , 
This is a mistake.
Change the documentation to English language.
good luck

**Review by RutiRozenberg — CHANGES_REQUESTED** [review]
In the files : `BLL/Services/Comment.cs` and `DAL/Repositories/Comment.cs` : 
Add a blank line before the newly added function.

**Comment by dinilandy** [comment]
I made the changes.

**Review by RutiRozenberg — COMMENTED** [review]
Excellent!!

**Review by RutiRozenberg — COMMENTED** [review]
👍

**Review by RutiRozenberg — APPROVED** [review]

**Comment by dinilandy** [comment]
You are a champion, there’s no one like you. 
Have a great rest of your day.

**Pull request merged**
